"""initial schema

Revision ID: 1d2fb893418a
Revises: 
Create Date: 2026-05-08 21:42:33.686315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2fb893418a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rules_json', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='runstatus'), nullable=False),
    sa.Column('target_model', sa.String(length=255), nullable=False),
    sa.Column('attacker_model', sa.String(length=255), nullable=False),
    sa.Column('categories', sa.Text(), nullable=False),
    sa.Column('strategies', sa.Text(), nullable=False),
    sa.Column('num_objectives', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('asr', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attacks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('strategy', sa.String(length=100), nullable=False),
    sa.Column('attack_complexity', sa.String(length=50), nullable=True),
    sa.Column('seed_prompt', sa.Text(), nullable=False),
    sa.Column('attack_success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attacks_category_strategy', 'attacks', ['run_id', 'category', 'strategy'], unique=False)
    op.create_index('ix_attacks_run_id', 'attacks', ['run_id'], unique=False)
    op.create_table('manifests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('manifest_yaml', sa.Text(), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('target_model_version', sa.String(length=255), nullable=True),
    sa.Column('attacker_model_version', sa.String(length=255), nullable=True),
    sa.Column('attack_set_version', sa.String(length=255), nullable=True),
    sa.Column('scorer_versions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index('ix_manifests_manifest_hash', 'manifests', ['manifest_hash'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attack_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attack_id'], ['attacks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attack_id')
    )
    op.create_index('ix_responses_attack_id', 'responses', ['attack_id'], unique=False)
    op.create_table('score_fusions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('response_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('composite_severity', sa.Float(), nullable=False),
    sa.Column('cpp_weight', sa.Float(), nullable=False),
    sa.Column('azure_cs_weight', sa.Float(), nullable=False),
    sa.Column('llm_judge_weight', sa.Float(), nullable=False),
    sa.Column('kappa_cpp_azure', sa.Float(), nullable=True),
    sa.Column('kappa_cpp_judge', sa.Float(), nullable=True),
    sa.Column('kappa_azure_judge', sa.Float(), nullable=True),
    sa.CheckConstraint('composite_severity >= 0 AND composite_severity <= 7', name='ck_fusions_severity_range'),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_score_fusions_response_id', 'score_fusions', ['response_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('response_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scorer_type', sa.Enum('cpp_engine', 'azure_cs', 'llm_judge', name='scorertype'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('matched_rules', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.CheckConstraint("scorer_type IN ('cpp_engine', 'azure_cs', 'llm_judge')", name='ck_scores_scorer_type'),
    sa.CheckConstraint('severity >= 0 AND severity <= 7', name='ck_scores_severity_range'),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scores_hot_path', 'scores', ['response_id', 'scorer_type', 'category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scores_hot_path', table_name='scores')
    op.drop_table('scores')
    op.drop_index('ix_score_fusions_response_id', table_name='score_fusions')
    op.drop_table('score_fusions')
    op.drop_index('ix_responses_attack_id', table_name='responses')
    op.drop_table('responses')
    op.drop_index('ix_manifests_manifest_hash', table_name='manifests')
    op.drop_table('manifests')
    op.drop_index('ix_attacks_run_id', table_name='attacks')
    op.drop_index('ix_attacks_category_strategy', table_name='attacks')
    op.drop_table('attacks')
    op.drop_table('runs')
    op.drop_table('policies')
    # ### end Alembic commands ###
